services:
  - type: web
    name: reddit-video-downloader
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    envVars:
      - key: PORT
        value: "8080"
